#!/data/data/com.termux/files/usr/bin/bash

echo
Menu(){
clear
echo '----------------------------------------------'
echo 'Atenção para as Opções, Não esquecer de alterar
      as Permições da pasta e Sub Pastas Vesão 1.0.45 '
echo '----------------------------------------------'
echo
echo 'Escolha a Versão do Jogo : '
echo 
echo '1. Global'
echo '2. Korea'
echo '3. Restaura Pubg Global e Kr'
echo '4. SAIR'
echo
echo -n 'Qual a opção desejada : '
read opcao # read le a variável opcao

# Recebe o valor da opção lida e executa a função correspondente
case $opcao in

1) Um ;; # funcao Um
2) Dois ;; # funcao Dois
3) Três ;;
4) Sair ;;
*) 'Opção desconhecida.' ; echo; Menu;;

esac
}


# funcao exibe 1
Um(){
echo 'Iniciando GLobal'

#am start -n com.tencent.ig/com.epicgames.ue4.SplashActivity	 

#sleep 15
#rm -rf /sdcard/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/core_patch_0.16.0.11462.pak
#rm -rf /sdcard/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/game_patch_0.16.0.11463.pak
#rm -rf /sdcard/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/game_patch_0.16.0.11464.pak
#rm -rf /sdcard/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/game_patch_0.16.0.11466.pak

echo
#$lobby
#echo " O jogo ja está Atualizou ?! pressione Enter para Continuar !!!"
#read lobby
am start -n com.tencent.ig/com.epicgames.ue4.SplashActivity
sleep 15
echo
echo " Alterando as permissões"

chmod -R 755 /data/data/com.tencent.ig/lib/libUE4.so
#chmod -R 755 /data/data/com.tencent.ig/lib/libtersafe.so
chmod -R 755 /data/data/com.tencent.ig/lib/libtprt.so

#tsu -c cp -R /storage/emulated/0/MALIKIG/libabase.so /data/data/com.tencent.ig/lib
#tsu -c cp -R /storage/emulated/0/MALIKIG/libBugly.so /data/data/com.tencent.ig/lib
tsu -c cp -R /storage/emulated/0/MALIKIG/libtprt.so /data/data/com.tencent.ig/lib
tsu -c cp -R /storage/emulated/0/MALIKIG/libUE4.so /data/data/com.tencent.ig/lib
#tsu -c cp -R /storage/emulated/0/MALIKIG/libzip.so /data/data/com.tencent.ig/lib
#tsu -c cp -R /storage/emulated/0/MALIKIG/libzlib.so /data/data/com.tencent.ig/lib

#tsu -c mv /data/data/com.tencent.ig/lib/libabase.so /storage/emulated/0/MALIKIG/backup
#tsu -c mv /data/data/com.tencent.ig/lib/libBugly.so /storage/emulated/0/MALIKIG/backup
tsu -c mv /data/data/com.tencent.ig/lib/libtprt.so /storage/emulated/0/MALIKIG/backup
tsu -c mv /data/data/com.tencent.ig/lib/libUE4.so /storage/emulated/0/MALIKIG/backup
#tsu -c mv /data/data/com.tencent.ig/lib/libzip.so /storage/emulated/0/MALIKIG/backup
#tsu -c mv /data/data/com.tencent.ig/lib/libzlib.so /storage/emulated/0/MALIKIG/backup

#chmod -R 755 /data/data/com.tencent.ig/lib/libabase.so 
#chmod -R 755 /data/data/com.tencent.ig/lib/libBugly.so 
chmod -R 2755 /data/data/com.tencent.ig/lib/libtprt.so
chmod -R 2755 /data/data/com.tencent.ig/lib/libUE4.so 
#chmod -R 000 /data/data/com.tencent.ig/lib/libzip.so 
#chmod -R 000 /data/data/com.tencent.ig/lib/libzlib.so 
#chmod -R 000 /data/data/com.tencent.ig/lib/libgcloud.so 




#CHUNK=$(yes '\x1E\xFF\x2F\xE1\x1C\xB0\x8D\xE2' | head -n 1500 | tr -d '\n'); NUMGEN=$(seq 4000 | tr '\r\n' ' '); printf $CHUNK%.0s $NUMGEN &> libUE4.so
#echo "Generating libtersafe.so"
#CHUNK=$(yes '\x1E\xFF\x2F\xE1\x1C\xB0\x8D\xE2' | head -n 100 | tr -d '\n'); NUMGEN=$(seq 4000 | tr '\r\n' ' '); printf $CHUNK%.0s $NUMGEN &> libtersafe.so
#echo "Generating libtprt.so"
#CHUNK=$(yes '\x1E\xFF\x2F\xE1\x1C\xB0\x8D\xE2' | head -n 20 | tr -d '\n'); NUMGEN=$(seq 4000 | tr '\r\n' ' '); printf $CHUNK%.0s $NUMGEN &> libtprt.so

#mv /data/data/com.tencent.ig/lib/libUE4.so ../
#mv /data/data/com.tencent.ig/lib/libtersafe.so ../
#mv /data/data/com.tencent.ig/lib/libtprt.so ../
#mv libUE4.so /data/data/com.tencent.ig/lib
#mv libtersafe.so /data/data/com.tencent.ig/lib
#mv libtprt.so /data/data/com.tencent.ig/lib


#chown 1000:1000 /data/data/com.tencent.ig/lib/libUE4.so
#chown 1000:1000 /data/data/com.tencent.ig/lib/libtersafe.so
#chown 1000:1000 /data/data/com.tencent.ig/lib/libtprt.so

#chmod -R 755 /data/data/com.tencent.ig/lib/libabase.so 
#chmod -R 755 /data/data/com.tencent.ig/lib/libBugly.so 
#chmod -R 664 /data/data/com.tencent.ig/lib/libtprt.so
#chmod -R 664 /data/data/com.tencent.ig/lib/libUE4.so 
#chmod -R 755 /data/data/com.tencent.ig/lib/libzip.so 
#chmod -R 755 /data/data/com.tencent.ig/lib/libzlib.so 


echo

echo

#codigo novo teste
#chmod -R 000 /data/data/com.tencent.ig/lib/libgcloud.so
#chmod -R 000 /data/data/com.tencent.ig/lib/libzip.so
#chmod -R 000 /data/data/com.tencent.ig/lib/libzlib.so
#chmod -R 000 /data/data/com.tencent.ig/databases/iMSDK.db
#codigo novo teste

echo 

echo
rm -rf /data/data/com.tencent.ig/lib
rm -rf /data/data/com.tencent.ig/databases/__hs__db_issues
rm -rf /data/data/com.tencent.ig/databases/__hs__db_issues-shm
rm -rf /data/data/com.tencent.ig/databases/__hs__db_issues-wal
rm -rf /data/data/com.tencent.ig/databases/__hs__db_key_values
rm -rf /data/data/com.tencent.ig/databases/__hs__db_key_values-shm
rm -rf /data/data/com.tencent.ig/databases/__hs__db_key_values-wal
rm -rf /data/data/com.tencent.ig/databases/__hs__db_properties
rm -rf /data/data/com.tencent.ig/databases/__hs__db_properties-shm
rm -rf /data/data/com.tencent.ig/databases/__hs__db_properties-wal
rm -rf /data/data/com.tencent.ig/databases/__hs__db_sessions
rm -rf /data/data/com.tencent.ig/databases/__hs__db_sessions-shm
rm -rf /data/data/com.tencent.ig/databases/__hs__db_sessions-wal
rm -rf /data/data/com.tencent.ig/databases/__hs__db_support_key_values
rm -rf /data/data/com.tencent.ig/databases/__hs__db_support_key_values-shm
rm -rf /data/data/com.tencent.ig/databases/__hs__db_support_key_values-wal
rm -rf /data/data/com.tencent.ig/databases/__hs_db_helpshift_users
rm -rf /data/data/com.tencent.ig/databases/__hs_db_helpshift_users-shm
rm -rf /data/data/com.tencent.ig/databases/__hs_db_helpshift_users-wal
rm -rf /data/data/com.tencent.ig/databases/__hs_log_store-shm
rm -rf /data/data/com.tencent.ig/databases/__hs_log_store-wal
rm -rf /data/data/com.tencent.ig/databases/__hs_log_store

echo "Script exclusivo Membros Clã Shot "
sleep 10

echo "Aguarde trabalhando nas Libs...."

echo "Trocando as permissões"

#chmod -R 755 /data/data/com.tencent.ig/lib/libabase.so 
#chmod -R 755 /data/data/com.tencent.ig/lib/libBugly.so 
#chmod -R 755 /data/data/com.tencent.ig/lib/libtprt.so
#chmod -R 755 /data/data/com.tencent.ig/lib/libUE4.so 
#chmod -R 755 /data/data/com.tencent.ig/lib/libzip.so 
#chmod -R 755 /data/data/com.tencent.ig/lib/libzlib.so 






echo " libs Trocadas "

sleep 3
echo "Alterando host"
iptables -I INPUT -s dlied1.qq.com -j DROP &>/dev/null
iptables -I INPUT -s cloud.gsdk.proximabeta.com -j DROP &>/dev/null
iptables -I INPUT -s report.helpshift.com -j DROP &>/dev/null
iptables -I INPUT -s report.qq.com -j DROP &>/dev/null
iptables -I INPUT -s report.syzs.qq.com -j DROP &>/dev/null
iptables -I INPUT -s sy.guanjia.qq.com -j DROP &>/dev/null
rm -rf /data/data/com.tencent.ig/databases/* > /dev/null
clear
echo
echo "pakeges ok "
echo
echo
echo 
echo
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/AntiCheat.ini 
tsu -c cp -R /storage/emulated/0/MALIKIG/AntiCheat.ini  /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android
echo "verifique a pasta com a porra do arquivo "
sleep 120
FUCKINGLOGS()
{

#codigo novo 

rm -rf /sdcard/Android/data/com.tencent.ig/cache
rm -rf /sdcard/Android/data/com.tencent.ig/files/ca-bundle.pem 	  
rm -rf /sdcard/Android/data/com.tencent.ig/files/tbslog  	  
rm -rf /sdcard/Android/data/com.tencent.ig/files/login-identifier.txt
rm -rf /sdcard/Android/data/com.tencent.ig/files/cacheFile.txt	
rm -rf /sdcard/Android/data/com.tencent.ig/files/vmpcloudconfig.json
rm -rf /sdcard/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs
rm -rf /sdcard/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/1375135419_47_0.16.0.11466_20191217120416_135842427_cures.ifs.cures
rm -rf /sdcard/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/1375135419_47_0.16.0.11466_20191217120416_135842427_cures.ifs.res
rm -rf /sdcard/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/1375135419_47_0.16.5.11560_20200108100228_1861002805_cures.ifs.res
rm -rf /sdcard/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/1950038955_3090_0.16.5.11560_20200108020124_1155095217_cures.ifs.res
rm -rf /sdcard/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/puffer_temp
rm -rf /sdcard/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/puffer_res.eifs
rm -rf /sdcard/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/apollo_reslist.flist
rm -rf /sdcard/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/PufferFileList.json
rm -rf /sdcard/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/filelist.json
rm -rf /sdcard/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/RoleInfo/RoleInfo.json
rm -rf /sdcard/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/UpdateInfo
rm -rf /sdcard/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Pandora
rm -rf /sdcard/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/Engine
rm -rf /sdcard/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/StatEventReportedFlag
rm -rf /sdcard/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/PufferTmpDir
rm -rf /storage/emulated/0/.backups
rm -rf /storage/emulated/0/tencent
rm -rf /data/data/com.tencent.ig/app_appcache
rm -rf /data/data/com.tencent.ig/app_bugly
rm -rf /data/data/com.tencent.ig/app_crashrecord
rm -rf /data/data/com.tencent.ig/cache
rm -rf /data/data/com.tencent.ig/code_cache
rm -rf /data/data/com.tencent.ig/files/iMSDK
rm -rf /data/data/com.tencent.ig/files/ss_tmp
rm -rf /data/data/com.tencent.ig/files/hawk_data
rm -rf /data/data/com.tencent.ig/files/AppEventsLogger.persistedevents
#fim codigo novo
#tentativa de bloqueio pra nao usar host 

iptables -I INPUT -s dlied1.qq.com -j DROP &>/dev/null
iptables -I INPUT -s dlied2.qq.com -j DROP &>/dev/null
iptables -I INPUT -s dlied3.qq.com -j DROP &>/dev/null
iptables -I INPUT -s dlied4.qq.com -j DROP &>/dev/null
iptables -I INPUT -s dlied5.qq.com -j DROP &>/dev/null
iptables -I INPUT -s dlied6.qq.com -j DROP &>/dev/null
iptables -I INPUT -s cloud.gsdk.proximabeta.com -j DROP &>/dev/null
iptables -I INPUT -s vmp.qq.com -j DROP &>/dev/null
iptables -I INPUT -s report.helpshift.com -j DROP &>/dev/null
iptables -I INPUT -s report.qq.com -j DROP &>/dev/null
iptables -I INPUT -s report.syzs.qq.com -j DROP &>/dev/null
iptables -I INPUT -s sy.guanjia.qq.com -j DROP &>/dev/null
iptables -I INPUT -s astat.bugly.qcloud.com -j DROP &>/dev/null


echo " Log Apagado "
}
PACKAGE='com.tencent.ig'
while [ $(pidof $PACKAGE) ]
do
FUCKINGLOGS
if [ ! $(pidof $PACKAGE) ]; then
break

fi
done


#tsu -c cp -R /data/app/com.tencent.ig* /lib/libUE4.so /data/data/com.tencent.ig/lib/

#tsu -c mv /storage/emulated/0/MALIKIG/backup/libabase.so /data/data/com.tencent.ig/lib
#tsu -c mv /storage/emulated/0/MALIKIG/backup/libBugly.so /data/data/com.tencent.ig/lib
tsu -c mv /storage/emulated/0/MALIKIG/backup/libtprt.so /data/data/com.tencent.ig/lib
tsu -c mv /storage/emulated/0/MALIKIG/backup/libUE4.so /data/data/com.tencent.ig/lib
#tsu -c mv /storage/emulated/0/MALIKIG/backup/libzip.so /data/data/com.tencent.ig/lib
#tsu -c mv /storage/emulated/0/MALIKIG/backup/libzlib.so /data/data/com.tencent.ig/lib

rm -rf /storage/emulated/0/MALIKIG/backup/*

pm install -r /data/app/com.tencent.ig*/base.apk

su -c iptables --flush
Menu
}

Dois(){
echo 'Iniciando Korea Aguarde'
echo 
echo
echo
echo "Script exclusivo Membros Clã Shot "

sleep 4


am start -n com.pubg.krmobile/com.epicgames.ue4.SplashActivity
clear
echo " "
sleep 14
echo " "
echo " "
echo " "
tsu -c chmod 2755 /data/data/com.pubg.krmobile/lib/libUE4.so
tsu -c chmod 2755 /data/data/com.pubg.krmobile/lib/libtprt.so
tsu -c chmod 2755 /data/data/com.pubg.krmobile/lib/libtersafe.so
tsu -c chmod 2775 /data/data/com.pubg.krmobile/cache/*
tsu -c chmod 777 /data/data/com.termux/files/usr/etc
#tsu -c mv /data/data/com.pubg.krmobile/lib/libUE4.so /storage/emulated/0/MALIKI/backup
tsu -c mv /data/data/com.pubg.krmobile/lib/libtprt.so /storage/emulated/0/MALIKI/backup
tsu -c mv /data/data/com.pubg.krmobile/lib/libtersafe.so /storage/emulated/0/MALIKI/backup
#tsu -c mv /storage/emulated/0/MALIKI/libUE4.so /data/data/com.pubg.krmobile/lib
tsu -c mv /storage/emulated/0/MALIKI/libtersafe.so /data/data/com.pubg.krmobile/lib
tsu -c mv /storage/emulated/0/MALIKI/libtprt.so /data/data/com.pubg.krmobile/lib
#tsu -c chmod 2755 /data/data/com.pubg.krmobile/lib/libUE4.so
#tsu -c chmod 2755 /data/data/com.pubg.krmobile/lib/libUE4.so
tsu -c chmod 000 /data/data/com.pubg.krmobile/lib/libtprt.so
tsu -c chmod 000 /data/data/com.pubg.krmobile/lib/libtersafe.so
tsu -c chmod 2775 /data/data/com.pubg.krmobile/cache/*
tsu -c chmod 777 /data/data/com.termux/files/usr/etc

sleep 10
tsu -c mv /storage/emulated/0/Android/data/com.pubg.krmobile/files/login-identifier.txt /storage/emulated/0/MALIKI/backup
#codigo novo
tsu -c cp -R /storage/emulated/0/MALIKI/core_patch_0.16.0.11462.pak  /storage/emulated/0/MALIKI/Pach
tsu -c cp -R /storage/emulated/0/MALIKI/core_patch_0.16.5.11560.pak  /storage/emulated/0/MALIKI/Pach
tsu -c cp -R /storage/emulated/0/MALIKI/game_patch_0.16.0.11463.pak  /storage/emulated/0/MALIKI/Pach
tsu -c cp -R /storage/emulated/0/MALIKI/game_patch_0.16.0.11464.pak  /storage/emulated/0/MALIKI/Pach
tsu -c cp -R /storage/emulated/0/MALIKI/game_patch_0.16.0.11466.pak  /storage/emulated/0/MALIKI/Pach
tsu -c cp -R /storage/emulated/0/MALIKI/game_patch_0.16.5.11562.pak  /storage/emulated/0/MALIKI/Pach
tsu -c cp -R /storage/emulated/0/MALIKI/GameErrorNoRecords  /storage/emulated/0/MALIKI/Pach
tsu -c cp -R /storage/emulated/0/MALIKI/SrcVersion.ini  /storage/emulated/0/MALIKI/Pach



tsu -c mv /storage/emulated/0/MALIKI/Pach/core_patch_0.16.0.11462.pak  /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks
tsu -c mv /storage/emulated/0/MALIKI/Pach/core_patch_0.16.5.11560.pak  /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks
tsu -c mv /storage/emulated/0/MALIKI/Pach/game_patch_0.16.0.11463.pak  /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks
tsu -c mv /storage/emulated/0/MALIKI/Pach/game_patch_0.16.0.11464.pak  /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks
tsu -c mv /storage/emulated/0/MALIKI/Pach/game_patch_0.16.0.11466.pak  /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks
tsu -c mv /storage/emulated/0/MALIKI/Pach/game_patch_0.16.5.11562.pak  /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks
tsu -c mv /storage/emulated/0/MALIKI/Pach/GameErrorNoRecords  /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved
tsu -c mv /storage/emulated/0/MALIKI/Pach/SrcVersion.ini  /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved

#tsu -c chmod 440 /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/core_patch_0.16.0.11462.pak
#tsu -c chmod 440 /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/core_patch_0.16.5.11560.pak
#tsu -c chmod 440 /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/game_patch_0.16.0.11463.pak
#tsu -c chmod 440 /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/game_patch_0.16.0.11464.pak
#tsu -c chmod 440 /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/game_patch_0.16.0.11466.pak 
#tsu -c chmod 440 /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/game_patch_0.16.5.11562.pak
#tsu -c chmod 440 /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/GameErrorNoRecords
#tsu -c chmod 440 /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SrcVersion.ini





echo "Pach Copiado"
echo " "
echo " "
sleep 4
echo " "
#echo "Troca de libs ok "
#echo " O jogo ja está no Lobby ?! pressione Enter para Iniciar limpeza !!!"
#read lobby

echo "Aguardando Carregar Cache"
sleep 100
while tsu -c   ps aux | grep -v grep | grep krmobile > /dev/empty
do
      echo "Apagando logs Automatico"
rm -rf  /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames/Season &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames/RoleInfo &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames/PersonSpace &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames/Match &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames/LobbyBubble &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames/GEM &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames/Loading &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames/Character &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames/Activity &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/RoleInfo/RoleInfo.json &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/cache/*
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/login-identifier.txt
rm -rf /data/data/com.pubg.krmobile/app_bugly/tomb_1565956570550.txt
rm -rf /data/data/com.pubg.krmobile/app_bugly/tomb_1565957246658.txt
rm -rf /data/data/com.pubg.krmobile/cache/*
echo "passou por todos comandos"
iptables -I INPUT -s dlied1.qq.com -j DROP &>/dev/null
iptables -I INPUT -s dlied2.qq.com -j DROP &>/dev/null
iptables -I INPUT -s dlied3.qq.com -j DROP &>/dev/null
iptables -I INPUT -s dlied4.qq.com -j DROP &>/dev/null
iptables -I INPUT -s dlied5.qq.com -j DROP &>/dev/null
iptables -I INPUT -s dlied6.qq.com -j DROP &>/dev/null
iptables -I INPUT -s cloud.gsdk.proximabeta.com -j DROP &>/dev/null
iptables -I INPUT -s vmp.qq.com -j DROP &>/dev/null
iptables -I INPUT -s report.helpshift.com -j DROP &>/dev/null
iptables -I INPUT -s report.qq.com -j DROP &>/dev/null
iptables -I INPUT -s report.syzs.qq.com -j DROP &>/dev/null
iptables -I INPUT -s sy.guanjia.qq.com -j DROP &>/dev/null
iptables -I INPUT -s astat.bugly.qcloud.com -j DROP &>/dev/null
echo "bloqueou Host"
done
echo "Jogo Encerrado Restaurando Arquivos  "
echo "
┈╭━━╮┈┈╭━━╮┈┈┈┈
┈┃◥◥┃┈┈┃▍▍┃┈┈┈┈
┗┫┊▇┣┛┗┫▃┊┣┛┈┈┈
┈╰┳┳╯┈┈╰┳┳╯┈┈┈┈
▔▔┗┗▔▔▔▔┛┛▔▔▔▔▔▔
"

#tsu -c mv /data/data/com.pubg.krmobile/lib/libUE4.so /storage/emulated/0/MALIKI
tsu -c mv /data/data/com.pubg.krmobile/lib/libtersafe.so /storage/emulated/0/MALIKI
tsu -c mv /data/data/com.pubg.krmobile/lib/libtprt.so /storage/emulated/0/MALIKI
t#su -c mv /storage/emulated/0/MALIKI/backup/libUE4.so /data/data/com.pubg.krmobile/lib
tsu -c mv /storage/emulated/0/MALIKI/backup/libtersafe.so /data/data/com.pubg.krmobile/lib
tsu -c mv /storage/emulated/0/MALIKI/backup/libtprt.so /data/data/com.pubg.krmobile/lib
tsu -c mv /storage/emulated/0/MALIKI/backup/login-identifier.txt  /storage/emulated/0/Android/data/com.pubg.krmobile/files
sleep 5
echo '10%'
clear
echo '40%'
clear
echo '100 %'
echo "completo retornando ao Menu"
sleep 4
Menu

}

Três(){
echo 'Restaurando Pubg Global e Kr!!!'

rm -rf /storage/emulated/0/MALIKI/backup/*
rm -rf /storage/emulated/0/MALIKIG/backup/*

pm install /data/app/com.tencent.ig*/base.apk
pm install /data/app/com.pubg.krmobile*/base.apk

#mv /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra /storage/emulated/0/Korea/Backup 
#mv /storage/emulated/0/Korea/mod/ShadowTrackerExtra /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/
echo "100% completa"
sleep 4
clear 
Menu
}

Sair(){

if [[ exit ]]; then
echo 'Exit'
echo
fi

}

# Primeira função a ser executada no programa.
Menu
