#!/data/data/com.termux/files/usr/bin/bash

echo
Menu(){
clear
echo '----------------------------------------------'
echo 'Atenção para as Opções, Não esquecer de alterar
      as Permições da pasta e Sub Pastas Vesão 1.0.45 '
echo '----------------------------------------------'
echo
echo 'Escolha a Versão do Jogo : '
echo 
echo '1. Restaura Original'
echo '2. Korea'
echo '3. Primeira Execução Kr'
echo '4. SAIR'
echo
echo -n 'Qual a opção desejada : '
read opcao # read le a variável opcao

# Recebe o valor da opção lida e executa a função correspondente
case $opcao in

1) Um ;; # funcao Um
2) Dois ;; # funcao Dois
3) Três ;;
4) Sair ;;
*) 'Opção desconhecida.' ; echo; Menu;;

esac
}


# funcao exibe 1
Um(){
echo 'Função desativada Retornando ao menu'

sleep 5 
clear
Menu
}

Dois(){
echo 'Iniciando Korea Aguarde'
echo 
echo
echo
echo "Script exclusivo Membros Clã Shot "

sleep 4

am start -n com.pubg.krmobile/com.epicgames.ue4.SplashActivity
clear
echo " "
sleep 10
echo " "
echo " "
echo " "
tsu -c chmod 2755 /data/data/com.pubg.krmobile/lib/libUE4.so
tsu -c chmod 2775 /data/data/com.pubg.krmobile/cache/*
tsu -c chmod 777 /data/data/com.termux/files/usr/etc
tsu -c mv /data/data/com.pubg.krmobile/lib/libUE4.so /storage/emulated/0/MALIKI/backup
tsu -c mv /storage/emulated/0/MALIKI/libUE4.so /data/data/com.pubg.krmobile/lib
tsu -c chmod 2755 /data/data/com.pubg.krmobile/lib/libUE4.so
sleep 10
tsu -c mv /storage/emulated/0/Android/data/com.pubg.krmobile/files/login-identifier.txt /storage/emulated/0/MALIKI/backup
echo " "
echo " "
sleep 4
echo " "
echo "Troca de libs ok "
echo
echo "Aguardando Carregar Cache"
sleep 25
while tsu -c   ps aux | grep -v grep | grep krmobile > /dev/empty
do
      echo "Apagando logs Automatico"
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/cache/*
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/RoleInfo/RoleInfo.json
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/PufferFileList.json
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/puffer_res.eifs
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/apollo_reslist.flist
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/1950038955_3090_0.14.0.11170_20190815172752_1287820889_cures.ifs.res
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/ca-bundle.pem
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/login-identifier.txt
rm -rf /data/data/com.pubg.krmobile/app_bugly/tomb_1565956570550.txt
rm -rf /data/data/com.pubg.krmobile/app_bugly/tomb_1565957246658.txt

done
echo "Jogo Encerrado Restaurando Arquivos  "
echo "
┈╭━━╮┈┈╭━━╮┈┈┈┈
┈┃◥◥┃┈┈┃▍▍┃┈┈┈┈
┗┫┊▇┣┛┗┫▃┊┣┛┈┈┈
┈╰┳┳╯┈┈╰┳┳╯┈┈┈┈
▔▔┗┗▔▔▔▔┛┛▔▔▔▔▔▔
"

tsu -c mv /data/data/com.pubg.krmobile/lib/libUE4.so /storage/emulated/0/MALIKI
tsu -c mv /storage/emulated/0/MALIKI/backup/libUE4.so /data/data/com.pubg.krmobile/lib
tsu -c mv /storage/emulated/0/MALIKI/backup/login-identifier.txt  /storage/emulated/0/Android/data/com.pubg.krmobile/files
sleep 5
echo '10%'
clear
echo '40%'
clear
echo '100 %'
echo "completo retornando ao Menu"
sleep 4
Menu

}

Três(){
echo 'Trocando a pasta ShadowTracker Aguarde !!!'
mv /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra /storage/emulated/0/Korea/Backup 
mv /storage/emulated/0/Korea/mod/ShadowTrackerExtra /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/
echo "100% completa"
sleep 4
clear 
Menu
}

Sair(){

if [[ exit ]]; then
echo 'Exit'
echo
fi

}

# Primeira função a ser executada no programa.
Menu
