#!/data/data/com.termux/files/usr/bin/bash

apt-get update
apt-get --assume-yes upgrade 
su -c 'setenforce 0'
apt-get --assume-yes install tsu
apt-get --assume-yes install wget
apt-get --assume-yes install git
tsu -c rm -rf pubg
tsu -c rm -rf inicial
tsu -c rm -rf conf
tsu -c chmod 777 /data/data/com.termux/files/usr/etc/bash.bashrc
tsu -c chmod 777 /data/data/com.termux/files/usr/etc/motd
tsu -c rm -rf /data/data/com.termux/files/usr/etc/bash.bashrc
tsu -c rm -rf /data/data/com.termux/files/usr/etc/motd

tsu -c git clone https://github.com/M4L1K1/pubg.git
tsu -c chmod 777 ./pubg
tsu -c chmod 777 ./conf
tsu -c chmod 777  pubg/bash.bashrc
tsu -c chmod 777  pubg/motd
tsu -c mv pubg/bash.bashrc /data/data/com.termux/files/usr/etc/
tsu -c mv pubg/motd /data/data/com.termux/files/usr/etc/
tsu -c mv pubg/inicial $HOME
tsu -c mv pubg/conf $HOME
tsu -c chmod a+x inicial
tsu -c chmod a+x conf
